#!/system/bin/sh
case $1 in
    ppp1)
	echo 0 > /proc/sys/net/ipv4/ip_forward;
	;;
esac

# Use interface name if linkname is not available
NAME=${LINKNAME:-"$1"}

/system/bin/setprop "net.$NAME.dns1" ""
/system/bin/setprop "net.$NAME.dns2" "" 
/system/bin/setprop "net.$NAME.local-ip" "" 
/system/bin/setprop "net.$NAME.remote-ip" "" 
/system/bin/setprop "net.$NAME.gw" ""

/system/bin/setprop "net.gprs.ppp-running" ""
/system/bin/setprop "net.pppoe.interface" ""
/system/bin/setprop "net.pppoe.status" "-2"

/system/bin/setprop "net.gprs.ppp-running" ""
